name: govulncheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-file: go.mod
